kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-run-sa-scc-rolebinding
  namespace: ocp-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline-run-sa
    namespace: ocp-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: ocp-pipeline  
subjects:
  - kind: ServiceAccount
    name: pipeline-run-sa
    namespace: ocp-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

