apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: https://github.com/Ankit07D/ocp-gitops.git
type: kubernetes.io/basic-auth
stringData:
  username: Ankit07D
  password: <token>
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: andubey
  password: <password>
