apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: my-pipeline-trigger-binding
spec:
  params:
  - name: git-url
    value: $(body.repository.url)
  - name: git-revision
    value: 'main'
  - name: img-tag
    value: $(body.head_commit.id)